### ISSUE TITLE
!!cookie as false won't work in lifecycle hook

### ISSUE THREAD

**Issue by janat08** [alfhen/vue-cookie#16]
for some reason it will produce true value if false with double ! to convert null value of cookie not created.

**Comment by janat08** [comment]
using base library there're no bugs.

**Comment by alfhen** [comment]
@janat08 Could you please elaborate? ie. show some example code a use case where the problem occurs.

**Comment by janat08** [comment]
mounted: function () {
    this.romanized = !(!(Cookie.get('romanized')))
    console.log('romanized', this.romanized, !!Cookie.get('romanize'))
  },

**Comment by alfhen** [comment]
Hmm, its seems you are using the Global Cookie function provided by tiny-cookie try doing 
``` javascript
this.$cookie.get('romanized');
```

**Comment by janat08** [comment]
No, using your package for global variant is what will fail

**Comment by alfhen** [comment]
@janat08, If you want to use the global ```Cookie.get()``` function, then I suggest that you use the tiny-cookie package directly in your project rather than relying on this package. This package supports two ways of interacting with cookies through either ```this.$cookie``` or ```Vue.cookie``` as described in the documentation.

**Comment by janat08** [comment]
would you try !!this.$cookie.get('stuf') yourself
