### ISSUE TITLE
getting an extra dot(.) in cookie domain

### ISSUE THREAD

**Issue by raghu64** [alfhen/vue-cookie#38]
Hi i have a scenario where i have to create a cookie with the current hostname as domain, but it's adding an extra dot(.) before the hostname.

```
let domain = location.hostname
window.$cookies.set('name', 'value', '12h', '/', domain)
```

Ex: expected domain for cookie: `abc.google.com` actual domain name set in cookie `.abc.google.com`

Thanks.

**Comment by casey-lee** [comment]
How were you able to resolve this issue?

**Comment by casey-lee** [comment]
Got it, don't specify the domain.
