### ISSUE TITLE
怎么能够删除一级域名的cookie

### ISSUE THREAD

**Issue by CrazedBob** [alfhen/vue-cookie#4]
我现在在二级域名下面 second.website.com怎么能删除.website.com的cookie？
没有找到方法。。。是否考虑添加一个

**Comment by alfhen** [comment]
Sorry I dont speak Chinese, but if google translate its correct; Are you trying to delete a cookie from subsite "second.website.com" in the main domain "website.com" ? 

Currently the plugin does not support altering cookies in a specific domain, but there is a open PR to add the functionality, I will look into making a change to the plugin, so cookie domains will be supported in the future, that should also fix your issue.

**Comment by CrazedBob** [comment]
Thank you for you answer.
I want in "secong.website.com" to delete the ".website.com" cookie.
Look forward to the release of the new version～！

**Comment by alfhen** [comment]
@CrazedBob You should be able to use the lateste realease to solve your problem: https://github.com/alfhen/vue-cookie/releases/tag/v1.1.0
