### ISSUE TITLE
webpack  build error

### ISSUE THREAD

**Issue by ningdb** [alfhen/vue-cookie#7]
![ec98d461-d044-4139-93a1-188cd7f1357e](https://cloud.githubusercontent.com/assets/532701/20296106/e9fbe9ea-ab43-11e6-86c9-72b275b68e04.png)

**Comment by alfhen** [comment]
@ningdb What version of vue-cookie are you using?
I am not that experienced in webpack as I mostly use laravel-elixir to handle the webpack logic for me. But I can try to assist you as best as I can.
Could you paste the code where you include vue-cookie and maybe your webpack conf?

**Comment by ningdb** [comment]
I am use the last vue webpack template is ok.thanks.

**Comment by alfhen** [comment]
@ningdb Thanks for reporting,
It should be solved in the latest release: v1.1.3 - https://github.com/alfhen/vue-cookie/releases/tag/v1.1.3

So update your package.json to ```"vue-cookie": "^1.1.3"``` and run ```npm update``` then it should work

**Comment by ningdb** [comment]
@alfhen thanks
