### ISSUE TITLE
isInteger ES6 browser support

### ISSUE THREAD

**Issue by timmetj** [alfhen/vue-cookie#8]
Hi,

I noticed you use the isInteger function on line 13. But this is not supported by all browsers like IE11 and older.
Is it maybe possible to adjust to make it browser compatible?

possible solution:
```
Number.isInteger = Number.isInteger || function(value) {
    return typeof value === "number" && 
           isFinite(value) && 
           Math.floor(value) === value;
};
```

**Comment by alfhen** [comment]
@timmetj Great idea, thanks to a PR by @jackie19 it is solved in the latest release 😄
